version: "3"
services:
  ubuntu_nginx:
    container_name: ubuntu_nginx
    image: ubuntu
    restart: on-failure
    volumes:
      - SIEM-ubuntu-app-1:/root
    command: ["sleep","infinity"]
    ports:
      - "2222:22"

volumes:
  SIEM-ubuntu-app-1:
    driver: local